#define SEL_COUNTER_ATOMIC
#define COUNTER_ATOMIC
#define TXOPT_ENABLE
#define COUNTER_CACHE_SIZE (8192/4)
//! SM change verfication cache size
#define VERIFICATION_CACHE_SIZE (8192/4)
// #define VERIFICATION_CACHE_SIZE (128)
#define VERIFICATION
#define DEDUP
#define DUP_RATE 50
#define DUP_LATENCY 321000
#define NONDUP_LATENCY 321000
#define BACKEND_PIPELINE_LATENCY 1800
#define BACKEND_PIPELINE_OPS 9999
#define BACKEND_PIPELINE_QUEUE 9999
